# Jekyll configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: 'Welcome to my site'
description: "&quotSharing knowledge is the most fundamental act of friendship. Because it is a way you can give something without loosing something&quot by Richard Stallman"

#short_url: 'https://qwertymarmot.github.io/'
google_analytics: G-P8PT9CR3L3
disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: '/jekylldev'
url: 'https://www.iambrandoncole.com'

# Permalinks
#permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs
plugins: [jekyll-paginate]


wikilinks:
attributes:
  enabled: true
# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

## Enable _notes Collection
collections:
    notes:
      output: true
      permalink: /notes/:title
      
      defaults:
      - scope:
          path: ""
          type: posts
        values:
          layout: Post
          permalink: /posts/:title
          content-type: post
      - scope:
          path: ""
          type: notes
        values:
          layout: Post
          content-type: notes 

feed:
  categories:
    - now
    - projects


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
#safe: false
#lsi: false
#username: jekyllt
#repo: jasper
#branch: master
#relative_source: ../jasper/
#destination: ../jasper-pages/
#production_url:  https://jekyllt.github.io/jasper/
#source_url:  https://github.com/jekyllt/jasper/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
  - .git
